# Taskfile.yml
version: '3'

tasks:
  # --- Exercise Definitions ---
  ap-A-ex-0:
    desc: Start all Appendix A Exercise 0 servers
    cmds:
      - task: _run-suite
        vars: { EX: "ap-A-ex-0" }

  ch-3-ex-1:
    desc: Start all Chapter 3 Exercise 1 servers
    cmds:
      - task: _run-suite
        vars: { EX: "ch-3-ex-1" }

  # --- Helpers ---
  _run-suite:
    internal: true
    deps:
      - task: _go-run
        vars: { EX: "{{.EX}}", DIR: "protectedResource"}
      - task: _go-run
        vars: { EX: "{{.EX}}", DIR: "authorizationServer"}
      - task: _go-run
        vars: { EX: "{{.EX}}", DIR: "client"}

  _go-run:
    internal: true
    cmds:
      - go run ./exercises/{{.EX}}/{{.DIR}}/main.go
